name: Sync Metadata

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout docs repository
        uses: actions/checkout@v4

      - name: Clone meteostat-python repository
        run: |
          git clone https://github.com/meteostat/meteostat-python.git
          cd meteostat-python
          git checkout next

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd meteostat-python
          pip install -e .

      - name: Generate JSON files
        run: |
          python - <<'EOF'
          import json
          from meteostat.parameters import DEFAULT_PARAMETERS
          from meteostat.providers.index import DEFAULT_PROVIDERS

          PARAMETERS = []
          PROVIDERS = []

          for parameter in DEFAULT_PARAMETERS:
              PARAMETERS.append({
                  "id": parameter.id,
                  "name": parameter.name,
                  "granularity": parameter.granularity,
                  "unit": parameter.unit,
                  "dtype": parameter.dtype,
              })

          for provider in DEFAULT_PROVIDERS:
              PROVIDERS.append({
                  "id": provider.id,
                  "name": provider.name,
                  "granularity": provider.granularity,
                  "parameters": provider.parameters
              })

          # Convert parameters to JSON
          with open('./parameters.json', 'w') as f:
              json.dump(PARAMETERS, f, indent=2)

          # Convert providers to JSON
          with open('./providers.json', 'w') as f:
              json.dump(PROVIDERS, f, indent=2)
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add static/parameters.json static/providers.json
          git commit -m "Update parameters and providers data" || exit 0
          git push